// Arabic name -> official English name. Used to backfill agencies.name_en once.
// Entities not listed fall back to the Arabic name in the English UI.
export const NAME_EN = {
  // Ministries
  'وزارة الدفاع': 'Ministry of Defense',
  'وزارة الداخلية': 'Ministry of Interior',
  'وزارة الخارجية': 'Ministry of Foreign Affairs',
  'وزارة الحرس الوطني': 'Ministry of National Guard',
  'وزارة المالية': 'Ministry of Finance',
  'وزارة الاقتصاد والتخطيط': 'Ministry of Economy and Planning',
  'وزارة الطاقة': 'Ministry of Energy',
  'وزارة الصناعة والثروة المعدنية': 'Ministry of Industry and Mineral Resources',
  'وزارة الاستثمار': 'Ministry of Investment',
  'وزارة التجارة': 'Ministry of Commerce',
  'وزارة الموارد البشرية والتنمية الاجتماعية': 'Ministry of Human Resources and Social Development',
  'وزارة التعليم': 'Ministry of Education',
  'وزارة الصحة': 'Ministry of Health',
  'وزارة العدل': 'Ministry of Justice',
  'وزارة الشؤون الإسلامية والدعوة والإرشاد': 'Ministry of Islamic Affairs, Dawah and Guidance',
  'وزارة الحج والعمرة': 'Ministry of Hajj and Umrah',
  'وزارة الثقافة': 'Ministry of Culture',
  'وزارة الإعلام': 'Ministry of Media',
  'وزارة الرياضة': 'Ministry of Sport',
  'وزارة السياحة': 'Ministry of Tourism',
  'وزارة النقل والخدمات اللوجستية': 'Ministry of Transport and Logistic Services',
  'وزارة البيئة والمياه والزراعة': 'Ministry of Environment, Water and Agriculture',
  'وزارة الشؤون البلدية والقروية والإسكان': 'Ministry of Municipal and Rural Affairs and Housing',
  'وزارة الاتصالات وتقنية المعلومات': 'Ministry of Communications and Information Technology',

  // Authorities
  'الهيئة السعودية للبيانات والذكاء الاصطناعي': 'Saudi Data & AI Authority (SDAIA)',
  'الهيئة السعودية للمدن الصناعية ومناطق التقنية': 'MODON',
  'الهيئة السعودية للمراجعين والمحاسبين': 'SOCPA',
  'الهيئة السعودية للمراجعين الداخليين': 'Saudi Internal Auditors Authority',
  'الهيئة السعودية للمياه': 'Saudi Water Authority',
  'الهيئة العامة للأمن الغذائي': 'General Food Security Authority',
  'الهيئة العامة للعناية بشؤون المسجد الحرام والمسجد النبوي': 'Authority for the Two Holy Mosques',
  'الهيئة العامة للمساحة والمعلومات الجيومكانية': 'General Authority for Survey & Geospatial Information',
  'الهيئة العامة للولاية على أموال القاصرين ومن في حكمهم': 'Authority for Minors Funds',
  'هيئة الزكاة والضريبة والجمارك': 'Zakat, Tax and Customs Authority (ZATCA)',
  'الهيئة العامة للطيران المدني': 'General Authority of Civil Aviation (GACA)',
  'هيئة السوق المالية': 'Capital Market Authority (CMA)',
  'الهيئة السعودية للملكية الفكرية': 'Saudi Authority for Intellectual Property (SAIP)',
  'الهيئة السعودية للمواصفات والمقاييس والجودة': 'Saudi Standards, Metrology and Quality Org (SASO)',
  'الهيئة العامة للغذاء والدواء': 'Saudi Food & Drug Authority (SFDA)',
  'الهيئة السعودية للسياحة': 'Saudi Tourism Authority',
  'الهيئة العامة للإحصاء': 'General Authority for Statistics (GASTAT)',
  'الهيئة العامة للمنشآت الصغيرة والمتوسطة (منشآت)': 'Monsha’at (SME Authority)',
  'هيئة الحكومة الرقمية': 'Digital Government Authority',
  'هيئة كفاءة الإنفاق والمشروعات الحكومية': 'Expenditure & Projects Efficiency Authority',
  'هيئة تنمية المحتوى المحلي والمشتريات الحكومية': 'Local Content & Government Procurement Authority',
  'الهيئة السعودية للبحر الأحمر': 'Saudi Red Sea Authority',
  'الهيئة العامة للترفيه': 'General Entertainment Authority',
  'الهيئة العامة للطرق': 'Roads General Authority',
  'الهيئة السعودية للمقاولين': 'Saudi Contractors Authority',
  'الهيئة العامة لعقارات الدولة': 'State Properties General Authority',

  // Companies (well-known)
  'نيوم': 'NEOM',
  'روشن': 'ROSHN',
  'شركة الدرعية': 'Diriyah Company',
  'البحر الأحمر العالمية': 'Red Sea Global',
  'القدية': 'Qiddiya',
  'لوسيد': 'Lucid',
  'أكوا باور': 'ACWA Power',
  'معادن': 'Maaden',
  'الشركة السعودية للصناعات العسكرية (SAMI)': 'SAMI',
  'stc': 'stc',
  'شركة علم': 'Elm',
  'مجموعة تداول السعودية': 'Saudi Tadawul Group',
  'البنك الأهلي السعودي': 'Saudi National Bank (SNB)',
  'شركة نوبكو': 'NUPCO',
  'الشركة الوطنية للتنمية الزراعية (نادك)': 'NADEC',
  'مجموعة MBC': 'MBC Group',
  'مصرف الراجحي': 'Al Rajhi Bank',
  'الشركة السعودية للصناعات الأساسية (سابك)': 'SABIC',
  'بنك الرياض': 'Riyad Bank',
  'مصرف الإنماء': 'Alinma Bank',
  'شركة موبايلي': 'Mobily',
  'مدينة الملك عبدالله الاقتصادية': 'King Abdullah Economic City (KAEC)',
  'مركز الملك عبدالله المالي (كافد)': 'KAFD',
  'مؤسسة مسك الخيرية': 'Misk Foundation',

  // Completed
  'مؤسسة سليمان بن عبدالعزيز الراجحي الخيرية': 'Sulaiman Al Rajhi Foundation',
  'تكافل الراجحي': 'Al Rajhi Takaful',
  'صندوق التنمية السياحي': 'Tourism Development Fund',
  'سنتر3 (center3)': 'center3',
  'الشركة السعودية لمراكز البيانات (SCCC) من stc': 'SCCC by stc',
  'إمداد من علم': 'Emdad by Elm',
}
