// Real dataset. Ministries = official Saudi list. Authorities = well-known Saudi
// authorities. Companies = major PIF-portfolio entities by sector. Logos are
// matched from local files by scripts/match-logos.mjs into server/logos-map.json.

// { name, url, desc }
export const MINISTRIES = [
  { name: 'وزارة الدفاع', url: 'https://www.mod.gov.sa', desc: 'الدفاع عن المملكة وإدارة القوات المسلحة.' },
  { name: 'وزارة الداخلية', url: 'https://www.moi.gov.sa', desc: 'الأمن الداخلي والخدمات المدنية والجوازات والمرور.' },
  { name: 'وزارة الخارجية', url: 'https://www.mofa.gov.sa', desc: 'إدارة العلاقات والسياسة الخارجية للمملكة.' },
  { name: 'وزارة الحرس الوطني', url: 'https://www.sang.gov.sa', desc: 'حماية المقدّرات الوطنية والدفاع عن المملكة.' },
  { name: 'وزارة المالية', url: 'https://www.mof.gov.sa', desc: 'إدارة المالية العامة والميزانية والإيرادات.' },
  { name: 'وزارة الاقتصاد والتخطيط', url: 'https://www.mep.gov.sa', desc: 'التخطيط الاقتصادي والتنموي ومتابعة الأداء.' },
  { name: 'وزارة الطاقة', url: 'https://www.moenergy.gov.sa', desc: 'تنظيم قطاع الطاقة والكهرباء والبترول.' },
  { name: 'وزارة الصناعة والثروة المعدنية', url: 'https://www.mim.gov.sa', desc: 'تنمية القطاع الصناعي والتعديني.' },
  { name: 'وزارة الاستثمار', url: 'https://www.misa.gov.sa', desc: 'تنمية وجذب وتمكين الاستثمار في المملكة.' },
  { name: 'وزارة التجارة', url: 'https://www.mc.gov.sa', desc: 'تنظيم النشاط التجاري وحماية المستهلك.' },
  { name: 'وزارة الموارد البشرية والتنمية الاجتماعية', url: 'https://www.hrsd.gov.sa', desc: 'سوق العمل والتنمية الاجتماعية والضمان.' },
  { name: 'وزارة التعليم', url: 'https://www.moe.gov.sa', desc: 'التعليم العام والجامعي والتدريب.' },
  { name: 'وزارة الصحة', url: 'https://www.moh.gov.sa', desc: 'القطاع الصحي وتقديم الخدمات الطبية.' },
  { name: 'وزارة العدل', url: 'https://www.moj.gov.sa', desc: 'القضاء والخدمات والتوثيق العدلي.' },
  { name: 'وزارة الشؤون الإسلامية والدعوة والإرشاد', url: 'https://www.moia.gov.sa', desc: 'شؤون المساجد والدعوة والإرشاد.' },
  { name: 'وزارة الحج والعمرة', url: 'https://www.haj.gov.sa', desc: 'تنظيم وخدمات الحج والعمرة.' },
  { name: 'وزارة الثقافة', url: 'https://www.moc.gov.sa', desc: 'تنمية القطاع الثقافي ودعم الفنون.' },
  { name: 'وزارة الإعلام', url: 'https://www.media.gov.sa', desc: 'تنظيم وتطوير القطاع الإعلامي.' },
  { name: 'وزارة الرياضة', url: 'https://www.mos.gov.sa', desc: 'تنمية القطاع الرياضي والأندية.' },
  { name: 'وزارة السياحة', url: 'https://www.mt.gov.sa', desc: 'تنمية القطاع السياحي والتراخيص.' },
  { name: 'وزارة النقل والخدمات اللوجستية', url: 'https://www.mot.gov.sa', desc: 'قطاع النقل والخدمات اللوجستية.' },
  { name: 'وزارة البيئة والمياه والزراعة', url: 'https://www.mewa.gov.sa', desc: 'البيئة والمياه والزراعة والثروة الحيوانية.' },
  { name: 'وزارة الشؤون البلدية والقروية والإسكان', url: 'https://www.momrah.gov.sa', desc: 'الخدمات البلدية والإسكان والتخطيط العمراني.' },
  { name: 'وزارة الاتصالات وتقنية المعلومات', url: 'https://www.mcit.gov.sa', desc: 'قطاع الاتصالات وتقنية المعلومات والتحول الرقمي.' },
]

// { name, url, desc }
export const AUTHORITIES = [
  { name: 'الهيئة السعودية للبيانات والذكاء الاصطناعي', url: 'https://sdaia.gov.sa', desc: 'تنظيم وتطوير البيانات والذكاء الاصطناعي.' },
  { name: 'الهيئة السعودية للمدن الصناعية ومناطق التقنية', url: 'https://modon.gov.sa', desc: 'تطوير وتشغيل المدن الصناعية (مدن).' },
  { name: 'الهيئة السعودية للمراجعين والمحاسبين', url: 'https://socpa.org.sa', desc: 'تنظيم مهنة المحاسبة والمراجعة.' },
  { name: 'الهيئة السعودية للمراجعين الداخليين', url: '', desc: 'تطوير مهنة المراجعة الداخلية في المملكة.' },
  { name: 'الهيئة السعودية للمياه', url: '', desc: 'تنظيم قطاع المياه في المملكة.' },
  { name: 'الهيئة العامة للأمن الغذائي', url: 'https://gfsa.gov.sa', desc: 'ضمان أمن واستدامة الغذاء.' },
  { name: 'الهيئة العامة للعناية بشؤون المسجد الحرام والمسجد النبوي', url: '', desc: 'العناية بشؤون الحرمين الشريفين.' },
  { name: 'الهيئة العامة للمساحة والمعلومات الجيومكانية', url: 'https://gasgi.gov.sa', desc: 'المساحة والمعلومات الجيومكانية.' },
  { name: 'الهيئة العامة للولاية على أموال القاصرين ومن في حكمهم', url: '', desc: 'إدارة أموال القاصرين ومن في حكمهم.' },
  { name: 'هيئة الزكاة والضريبة والجمارك', url: 'https://zatca.gov.sa', desc: 'تحصيل الزكاة والضرائب والجمارك.' },
  { name: 'الهيئة العامة للطيران المدني', url: 'https://gaca.gov.sa', desc: 'تنظيم قطاع الطيران المدني والمطارات.' },
  { name: 'هيئة السوق المالية', url: 'https://cma.org.sa', desc: 'تنظيم ومراقبة السوق المالية.' },
  { name: 'الهيئة السعودية للملكية الفكرية', url: 'https://saip.gov.sa', desc: 'تنظيم وحماية الملكية الفكرية.' },
  { name: 'الهيئة السعودية للمواصفات والمقاييس والجودة', url: 'https://saso.gov.sa', desc: 'المواصفات والمقاييس والجودة.' },
  { name: 'الهيئة العامة للغذاء والدواء', url: 'https://sfda.gov.sa', desc: 'سلامة الغذاء والدواء والأجهزة الطبية.' },
  { name: 'الهيئة السعودية للسياحة', url: 'https://scth.gov.sa', desc: 'تطوير وتسويق الوجهات السياحية.' },
  { name: 'الهيئة العامة للإحصاء', url: 'https://stats.gov.sa', desc: 'إنتاج الإحصاءات الرسمية للمملكة.' },
  { name: 'الهيئة العامة للمنشآت الصغيرة والمتوسطة (منشآت)', url: 'https://monshaat.gov.sa', desc: 'دعم وتمكين المنشآت الصغيرة والمتوسطة.' },
  { name: 'هيئة الحكومة الرقمية', url: 'https://dga.gov.sa', desc: 'تنظيم وتطوير الحكومة الرقمية.' },
  { name: 'هيئة كفاءة الإنفاق والمشروعات الحكومية', url: 'https://expro.gov.sa', desc: 'رفع كفاءة الإنفاق والمشروعات الحكومية.' },
  { name: 'هيئة تنمية المحتوى المحلي والمشتريات الحكومية', url: 'https://lcgpa.gov.sa', desc: 'تنمية المحتوى المحلي والمشتريات الحكومية.' },
  { name: 'الهيئة السعودية للبحر الأحمر', url: '', desc: 'تنظيم وتطوير الأنشطة على البحر الأحمر.' },
  { name: 'الهيئة العامة للترفيه', url: 'https://gea.gov.sa', desc: 'تنظيم وتطوير قطاع الترفيه.' },
  { name: 'الهيئة العامة للطرق', url: 'https://roads.gov.sa', desc: 'تطوير وتشغيل شبكة الطرق.' },
  { name: 'الهيئة السعودية للمقاولين', url: '', desc: 'تنظيم وتطوير قطاع المقاولات.' },
  { name: 'الهيئة العامة لعقارات الدولة', url: '', desc: 'إدارة عقارات الدولة.' },
]

// { name, sector, url, desc }
export const COMPANIES = [
  { name: 'نيوم', sector: 'العقارات والبنية التحتية', url: 'https://www.neom.com', desc: 'مدينة ومنطقة اقتصادية مستقبلية شمال غرب المملكة.' },
  { name: 'روشن', sector: 'العقارات والبنية التحتية', url: 'https://www.roshn.sa', desc: 'مطوّر عقاري وطني لمجتمعات سكنية متكاملة.' },
  { name: 'شركة الدرعية', sector: 'العقارات والبنية التحتية', url: 'https://www.diriyah.sa', desc: 'تطوير الدرعية كوجهة ثقافية وتراثية عالمية.' },
  { name: 'شركة سدن للتطوير', sector: 'العقارات والبنية التحتية', url: '', desc: 'تطوير وجهات عقارية وسياحية في عسير.' },
  { name: 'البحر الأحمر العالمية', sector: 'السياحة والترفيه', url: 'https://www.redseaglobal.com', desc: 'تطوير وجهات سياحية فاخرة ومستدامة.' },
  { name: 'القدية', sector: 'السياحة والترفيه', url: 'https://qiddiya.com', desc: 'عاصمة الترفيه والرياضة والثقافة.' },
  { name: 'كروز السعودية', sector: 'السياحة والترفيه', url: 'https://cruisesaudi.com', desc: 'تطوير قطاع السياحة البحرية والرحلات.' },
  { name: 'شركة صناعة الترفيه (سيفن)', sector: 'السياحة والترفيه', url: 'https://seven.sa', desc: 'تطوير وجهات ترفيهية في أنحاء المملكة.' },
  { name: 'لوسيد', sector: 'النقل واللوجستيات', url: 'https://www.lucidmotors.com', desc: 'تصنيع السيارات الكهربائية الفاخرة.' },
  { name: 'سير', sector: 'النقل واللوجستيات', url: 'https://www.ceermotors.com', desc: 'أول علامة سعودية للسيارات الكهربائية.' },
  { name: 'الرياض للطيران', sector: 'النقل واللوجستيات', url: 'https://www.riyadhair.com', desc: 'الناقل الجوي الوطني الجديد ومقره الرياض.' },
  { name: 'شركة مطارات الرياض', sector: 'النقل واللوجستيات', url: 'https://www.riyadhairports.com', desc: 'تشغيل وتطوير مطار الرياض.' },
  { name: 'أكوا باور', sector: 'الطاقة والمياه', url: 'https://www.acwapower.com', desc: 'تطوير محطات الطاقة وتحلية المياه.' },
  { name: 'معادن', sector: 'الصناعة والتعدين', url: 'https://www.maaden.com.sa', desc: 'التعدين ومعالجة المعادن في المملكة.' },
  { name: 'الشركة السعودية للصناعات العسكرية (SAMI)', sector: 'الصناعة والتعدين', url: 'https://www.sami.com.sa', desc: 'تطوير الصناعات الدفاعية والعسكرية.' },
  { name: 'stc', sector: 'التقنية والاتصالات', url: 'https://www.stc.com.sa', desc: 'مجموعة رائدة في الاتصالات والتقنية.' },
  { name: 'شركة علم', sector: 'التقنية والاتصالات', url: 'https://www.elm.sa', desc: 'حلول رقمية وأعمال آمنة للقطاعين.' },
  { name: 'مجموعة تداول السعودية', sector: 'الخدمات المالية', url: 'https://www.saudiexchange.sa', desc: 'مجموعة السوق المالية السعودية.' },
  { name: 'البنك الأهلي السعودي', sector: 'الخدمات المالية', url: 'https://www.alahli.com', desc: 'أحد أكبر البنوك في المملكة.' },
  { name: 'شركة نوبكو', sector: 'الرعاية الصحية', url: 'https://www.nupco.com', desc: 'الشراء والإمداد الموحّد للقطاع الصحي.' },
  { name: 'شركة الصحة القابضة', sector: 'الرعاية الصحية', url: '', desc: 'تطوير وتشغيل تجمّعات الرعاية الصحية.' },
  { name: 'شركة القهوة السعودية', sector: 'الأغذية والزراعة', url: '', desc: 'تطوير صناعة القهوة السعودية.' },
  { name: 'شركة تطوير المنتجات الحلال', sector: 'الأغذية والزراعة', url: '', desc: 'تطوير وتمكين قطاع المنتجات الحلال.' },
  { name: 'الشركة الوطنية للتنمية الزراعية (نادك)', sector: 'الأغذية والزراعة', url: 'https://www.nadec.com.sa', desc: 'إنتاج الأغذية والمنتجات الزراعية.' },
  { name: 'مجموعة MBC', sector: 'الإعلام والرياضة', url: 'https://www.mbc.net', desc: 'أكبر مجموعة إعلامية في المنطقة.' },
  { name: 'نادي الهلال', sector: 'الإعلام والرياضة', url: 'https://www.alhilal.com', desc: 'نادٍ رياضي سعودي.' },
  { name: 'نادي النصر', sector: 'الإعلام والرياضة', url: 'https://www.alnassr.sa', desc: 'نادٍ رياضي سعودي.' },
  { name: 'نادي الاتحاد', sector: 'الإعلام والرياضة', url: 'https://www.ittihad.com.sa', desc: 'نادٍ رياضي سعودي.' },
  { name: 'نادي الأهلي', sector: 'الإعلام والرياضة', url: 'https://www.alahli.com.sa', desc: 'نادٍ رياضي سعودي.' },
]

// Companies added as 'completed' (مكتمل) with their logos from the local "completed" folder.
// { name, sector, url, desc, logo }
export const COMPLETED = [
  { name: 'مؤسسة سليمان بن عبدالعزيز الراجحي الخيرية', sector: 'القطاع غير الربحي', url: 'https://srcf.org.sa', desc: 'مؤسسة وقفية خيرية تعنى بالتنمية الاجتماعية والإنسانية.', logo: '/logos/completed/al-rajhi-foundation.webp' },
  { name: 'تكافل الراجحي', sector: 'الخدمات المالية', url: 'https://www.alrajhitakaful.com', desc: 'شركة تأمين تعاوني (تكافل) سعودية.', logo: '/logos/completed/al-rajhi-takaful.png' },
  { name: 'صندوق التنمية السياحي', sector: 'الخدمات المالية', url: 'https://tdf.gov.sa', desc: 'تمويل ودعم مشاريع ومنشآت القطاع السياحي.', logo: '/logos/completed/tourism-dev-fund.jpg' },
  { name: 'سنتر3 (center3)', sector: 'التقنية والاتصالات', url: 'https://center3.com', desc: 'شركة متخصصة في مراكز البيانات والربط الرقمي.', logo: '/logos/completed/center3.jpg' },
  { name: 'الشركة السعودية لمراكز البيانات (SCCC) من stc', sector: 'التقنية والاتصالات', url: 'https://sccc.sa', desc: 'خدمات مراكز البيانات والاستضافة والحوسبة السحابية.', logo: '/logos/completed/sccc-stc.jpg' },
  { name: 'إمداد من علم', sector: 'التقنية والاتصالات', url: 'https://elm.sa', desc: 'حلول إدارة المستودعات والإمداد التابعة لشركة علم.', logo: '/logos/completed/emdad-elm.png' },
  { name: '½M', sector: '', url: '', desc: '', logo: '/logos/completed/half-m.png' },
]

// Companies created from recent logo downloads (status متوفر). { name, sector, url, logo }
export const RECENT = [
  { name: 'شركة عبدالله العثيم للاستثمار العقاري والتنمية', sector: 'العقارات والبنية التحتية', url: 'https://alothaimre.com', logo: '/logos/recent/othaim-re.svg' },
  { name: 'مجموعة الشايع', sector: 'تجارة التجزئة', url: 'https://www.alshaya.com', logo: '/logos/recent/alshaya.webp' },
  { name: 'مصرف الراجحي', sector: 'الخدمات المالية', url: 'https://www.alrajhibank.com.sa', logo: '/logos/recent/alrajhi-bank.png' },
  { name: 'شركة الفنار', sector: 'الطاقة والمياه', url: 'https://www.alfanar.com', logo: '/logos/recent/alfanar.png' },
  { name: 'صندوق التنمية الثقافي', sector: 'الخدمات المالية', url: 'https://cdf.gov.sa', logo: '/logos/recent/cdf.svg' },
  { name: 'أسمنت المنطقة الشرقية', sector: 'الصناعة والتعدين', url: 'https://www.epcco.com.sa', logo: '/logos/recent/epcc.png' },
  { name: 'شركة جدة المركزية', sector: 'العقارات والبنية التحتية', url: 'https://jeddahcentral.com', logo: '/logos/recent/jcdc.png' },
  { name: 'مركز الملك عبدالله المالي (كافد)', sector: 'العقارات والبنية التحتية', url: 'https://www.kafd.sa', logo: '/logos/recent/kafd.png' },
  { name: 'شركة ليجام الرياضية (وقت اللياقة)', sector: 'السياحة والترفيه', url: 'https://www.leejam.com.sa', logo: '/logos/recent/leejam.jpg' },
  { name: 'الشركة السعودية للصناعات الأساسية (سابك)', sector: 'الصناعة والتعدين', url: 'https://www.sabic.com', logo: '/logos/recent/sabic.png' },
  { name: 'مدى', sector: 'التقنية والاتصالات', url: 'https://mada.com.sa', logo: '/logos/recent/mada.svg' },
  { name: 'شركة مرافق', sector: 'الطاقة والمياه', url: 'https://www.marafiq.com.sa', logo: '/logos/recent/marafiq.png' },
  { name: 'مؤسسة مسك الخيرية', sector: 'القطاع غير الربحي', url: 'https://misk.org.sa', logo: '/logos/recent/misk.png' },
  { name: 'شركة موبايلي', sector: 'التقنية والاتصالات', url: 'https://www.mobily.com.sa', logo: '/logos/recent/mobily.png' },
  { name: 'شركة مرني', sector: 'التقنية والاتصالات', url: 'https://morni.com', logo: '/logos/recent/morni.png' },
  { name: 'منصة مدد', sector: 'التقنية والاتصالات', url: 'https://mudad.com.sa', logo: '/logos/recent/mudad.svg' },
  { name: 'منصة مقيم', sector: 'التقنية والاتصالات', url: 'https://muqeem.sa', logo: '/logos/recent/muqeem.svg' },
  { name: 'شركة بنده للتجزئة', sector: 'تجارة التجزئة', url: 'https://panda.com.sa', logo: '/logos/recent/panda.png' },
  { name: 'منصة قوى', sector: 'التقنية والاتصالات', url: 'https://www.qiwa.sa', logo: '/logos/recent/qiwa.svg' },
  { name: 'أسمنت القصيم', sector: 'الصناعة والتعدين', url: 'https://qcc.com.sa', logo: '/logos/recent/qassim-cement.png' },
  { name: 'بنك الرياض', sector: 'الخدمات المالية', url: 'https://www.riyadbank.com', logo: '/logos/recent/riyad-bank.png' },
  { name: 'شركة رؤى المدينة', sector: 'العقارات والبنية التحتية', url: 'https://www.ruaalmadinah.com', logo: '/logos/recent/rua-almadinah.png' },
  { name: 'شركة سلاسة', sector: 'النقل واللوجستيات', url: 'https://salasa.com', logo: '/logos/recent/salasa.png' },
  { name: 'شركة سنابل للاستثمارات', sector: 'الخدمات المالية', url: 'https://www.sanabil.com', logo: '/logos/recent/sanabil.png' },
  { name: 'الشركة السعودية للسيراميك', sector: 'الصناعة والتعدين', url: 'https://www.saudiceramics.com', logo: '/logos/recent/saudi-ceramic.png' },
  { name: 'شركة شربتلي', sector: 'الأغذية والزراعة', url: '', logo: '/logos/recent/sharbatly.svg' },
  { name: 'حلول (Solutions by stc)', sector: 'التقنية والاتصالات', url: 'https://solutions.com.sa', logo: '/logos/recent/solutions-stc.png' },
  { name: 'أسمنت المنطقة الجنوبية', sector: 'الصناعة والتعدين', url: 'https://www.spcc.com.sa', logo: '/logos/recent/spcc.png' },
  { name: 'الشركة الوطنية للنقل البحري (البحري)', sector: 'النقل واللوجستيات', url: 'https://www.bahri.sa', logo: '/logos/recent/bahri.png' },
  { name: 'أسمنت ينبع', sector: 'الصناعة والتعدين', url: 'https://www.yanbucement.com', logo: '/logos/recent/yanbu-cement.png' },
  { name: 'شركة آلات', sector: 'الصناعة والتعدين', url: 'https://alat.com', logo: '/logos/recent/alat.svg' },
  { name: 'مصرف الإنماء', sector: 'الخدمات المالية', url: 'https://www.alinma.com', logo: '/logos/recent/alinma.png' },
  { name: 'مدينة الملك عبدالله الاقتصادية', sector: 'العقارات والبنية التحتية', url: 'https://www.kaec.net', logo: '/logos/recent/kaec.png' },
  { name: 'شركة فودكس', sector: 'التقنية والاتصالات', url: 'https://www.foodics.com', logo: '/logos/recent/foodics.svg' },
  { name: 'شركة هيومين', sector: 'التقنية والاتصالات', url: 'https://humain.ai', logo: '/logos/recent/humain.png' },
  { name: 'شركة لين', sector: 'التقنية والاتصالات', url: 'https://www.lean.sa', logo: '/logos/recent/lean.svg' },
  { name: 'شركة دان', sector: 'السياحة والترفيه', url: '', logo: '/logos/recent/dan.svg' },
]

// Targeted-clients import (one-time). Accounts + their reserved companies.
export const TARGET_USERS = [
  { phone: '0503288883', name: 'خالد الفريح', nickname: 'أبو محمد' },
  { phone: '0539053955', name: 'زياد الرشيد', nickname: 'أبو بدر' },
  { phone: '0562808070', name: 'فيصل العتيبي', nickname: 'أبو لافي' },
  { phone: '0547670670', name: 'حجاب الحازمي', nickname: 'أبو البراء' },
  { phone: '0505110033', name: 'رائد الغامدي', nickname: 'أبو محمد' },
  { phone: '0550882021', name: 'ياسر الخليفي', nickname: 'أبو تالا' },
  { phone: '0568585599', name: 'نواف الحكمي', nickname: 'حبيبنا نواف' },
  { phone: '0583999958', name: 'يوسف مندورة', nickname: 'أبو ريم' },
  { phone: '0561110110', name: 'عبدالله الحبابي', nickname: 'أبو مناحي' },
]

// { name (exact catalog name if it exists, else created), phone (owner) }
export const TARGET_ASSIGNMENTS = [
  { name: 'شركة الصحة القابضة', phone: '0503288883' },
  { name: 'شركة موبايلي', phone: '0503288883' },
  { name: 'حلول (Solutions by stc)', phone: '0539053955' },
  { name: 'موهبة', phone: '0539053955' },
  { name: 'TAWAL (توال)', phone: '0539053955' },
  { name: 'صندوق التنمية الثقافي', phone: '0539053955' },
  { name: 'Chanel', phone: '0539053955' },
  { name: 'سرار (Sirar by stc)', phone: '0539053955' },
  { name: 'D360 Bank', phone: '0562808070' },
  { name: 'برق (Barq)', phone: '0562808070' },
  { name: 'صندوق الاستثمارات العامة (PIF)', phone: '0562808070' },
  { name: 'وزارة السياحة', phone: '0547670670' },
  { name: 'وزارة الشؤون البلدية والقروية والإسكان', phone: '0547670670' },
  { name: 'وزارة الاتصالات وتقنية المعلومات', phone: '0547670670' },
  { name: 'DR العقارية', phone: '0505110033' },
  { name: 'الأندلس العقارية', phone: '0505110033' },
  { name: 'شركة علم', phone: '0505110033' },
  { name: 'stc الكويت', phone: '0550882021' },
  { name: 'البنك الأهلي السعودي (SNB)', phone: '0568585599' },
  { name: 'بنك الرياض', phone: '0568585599' },
  { name: 'الشركة السعودية للصناعات العسكرية (SAMI)', phone: '0568585599' },
  { name: 'مصرف الراجحي', phone: '0568585599' },
  { name: 'شركة الدرعية', phone: '0568585599' },
  { name: 'هيئة تنمية المحتوى المحلي والمشتريات الحكومية', phone: '0568585599' },
  { name: 'البنك المركزي السعودي (ساما)', phone: '0568585599' },
  { name: 'البنك السعودي للاستثمار', phone: '0568585599' },
  { name: 'الدرع العربي للتأمين', phone: '0583999958' },
  { name: 'إتقان', phone: '0583999958' },
  { name: 'مصرف الإنماء', phone: '0561110110' },
  { name: 'مركز الملك عبدالله المالي (كافد)', phone: '0561110110' },
  { name: 'شركة نوبكو', phone: '0561110110' },
  { name: 'الشركة السعودية للصناعات الأساسية (سابك)', phone: '0561110110' },
  { name: 'شركة ليجام الرياضية (وقت اللياقة)', phone: '0561110110' },
  { name: 'أسمنت أم القرى', phone: '0561110110' },
]
