// Auto-generated from saudi_exchange_logos/companies.csv (Tadawul-listed entities).
export const TADAWUL = [
  {"name": "المصافي", "logo": "/logos/tadawul/2030.png", "url": "https://www.google.com/finance/quote/2030:TADAWUL", "brief": "المصافي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2030."},
  {"name": "أرامكو السعودية", "logo": "/logos/tadawul/2222.png", "url": "https://www.google.com/finance/quote/2222:TADAWUL", "brief": "أرامكو السعودية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2222."},
  {"name": "بترو رابغ", "logo": "/logos/tadawul/2380.png", "url": "https://www.google.com/finance/quote/2380:TADAWUL", "brief": "بترو رابغ — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2380."},
  {"name": "الحفر العربية", "logo": "/logos/tadawul/2381.png", "url": "https://www.google.com/finance/quote/2381:TADAWUL", "brief": "الحفر العربية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2381."},
  {"name": "أديس", "logo": "/logos/tadawul/2382.png", "url": "https://www.google.com/finance/quote/2382:TADAWUL", "brief": "أديس — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2382."},
  {"name": "البحري", "logo": "/logos/tadawul/4030.png", "url": "https://www.google.com/finance/quote/4030:TADAWUL", "brief": "البحري — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4030."},
  {"name": "تكوين", "logo": "/logos/tadawul/1201.png", "url": "https://www.google.com/finance/quote/1201:TADAWUL", "brief": "تكوين — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1201."},
  {"name": "مبكو", "logo": "/logos/tadawul/1202.png", "url": "https://www.google.com/finance/quote/1202:TADAWUL", "brief": "مبكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1202."},
  {"name": "بي سي آي", "logo": "/logos/tadawul/1210.png", "url": "https://www.google.com/finance/quote/1210:TADAWUL", "brief": "بي سي آي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1210."},
  {"name": "معادن", "logo": "/logos/tadawul/1211.png", "url": "https://www.google.com/finance/quote/1211:TADAWUL", "brief": "معادن — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1211."},
  {"name": "أسلاك", "logo": "/logos/tadawul/1301.png", "url": "https://www.google.com/finance/quote/1301:TADAWUL", "brief": "أسلاك — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1301."},
  {"name": "اليمامة للحديد", "logo": "/logos/tadawul/1304.png", "url": "https://www.google.com/finance/quote/1304:TADAWUL", "brief": "اليمامة للحديد — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1304."},
  {"name": "أنابيب السعودية", "logo": "/logos/tadawul/1320.png", "url": "https://www.google.com/finance/quote/1320:TADAWUL", "brief": "أنابيب السعودية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1320."},
  {"name": "أنابيب الشرق", "logo": "/logos/tadawul/1321.png", "url": "https://www.google.com/finance/quote/1321:TADAWUL", "brief": "أنابيب الشرق — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1321."},
  {"name": "أماك", "logo": "/logos/tadawul/1322.png", "url": "https://www.google.com/finance/quote/1322:TADAWUL", "brief": "أماك — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1322."},
  {"name": "يو سي آي سي", "logo": "/logos/tadawul/1323.png", "url": "https://www.google.com/finance/quote/1323:TADAWUL", "brief": "يو سي آي سي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1323."},
  {"name": "صالح الراشد", "logo": "/logos/tadawul/1324.png", "url": "https://www.google.com/finance/quote/1324:TADAWUL", "brief": "صالح الراشد — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1324."},
  {"name": "كيمانول", "logo": "/logos/tadawul/2001.png", "url": "https://www.google.com/finance/quote/2001:TADAWUL", "brief": "كيمانول — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2001."},
  {"name": "سابك", "logo": "/logos/tadawul/2010.png", "url": "https://www.google.com/finance/quote/2010:TADAWUL", "brief": "سابك — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2010."},
  {"name": "سابك للمغذيات الزراعية", "logo": "/logos/tadawul/2020.png", "url": "https://www.google.com/finance/quote/2020:TADAWUL", "brief": "سابك للمغذيات الزراعية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2020."},
  {"name": "التصنيع", "logo": "/logos/tadawul/2060.png", "url": "https://www.google.com/finance/quote/2060:TADAWUL", "brief": "التصنيع — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2060."},
  {"name": "جبسكو", "logo": "/logos/tadawul/2090.png", "url": "https://www.google.com/finance/quote/2090:TADAWUL", "brief": "جبسكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2090."},
  {"name": "زجاج", "logo": "/logos/tadawul/2150.png", "url": "https://www.google.com/finance/quote/2150:TADAWUL", "brief": "زجاج — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2150."},
  {"name": "اللجين", "logo": "/logos/tadawul/2170.png", "url": "https://www.google.com/finance/quote/2170:TADAWUL", "brief": "اللجين — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2170."},
  {"name": "فيبكو", "logo": "/logos/tadawul/2180.png", "url": "https://www.google.com/finance/quote/2180:TADAWUL", "brief": "فيبكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2180."},
  {"name": "أنابيب", "logo": "/logos/tadawul/2200.png", "url": "https://www.google.com/finance/quote/2200:TADAWUL", "brief": "أنابيب — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2200."},
  {"name": "نماء للكيماويات", "logo": "/logos/tadawul/2210.png", "url": "https://www.google.com/finance/quote/2210:TADAWUL", "brief": "نماء للكيماويات — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2210."},
  {"name": "معدنية", "logo": "/logos/tadawul/2220.png", "url": "https://www.google.com/finance/quote/2220:TADAWUL", "brief": "معدنية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2220."},
  {"name": "لوبريف", "logo": "/logos/tadawul/2223.png", "url": "https://www.google.com/finance/quote/2223:TADAWUL", "brief": "لوبريف — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2223."},
  {"name": "صناعات", "logo": "/logos/tadawul/2240.png", "url": "https://www.google.com/finance/quote/2240:TADAWUL", "brief": "صناعات — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2240."},
  {"name": "المجموعة السعودية", "logo": "/logos/tadawul/2250.png", "url": "https://www.google.com/finance/quote/2250:TADAWUL", "brief": "المجموعة السعودية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2250."},
  {"name": "ينساب", "logo": "/logos/tadawul/2290.png", "url": "https://www.google.com/finance/quote/2290:TADAWUL", "brief": "ينساب — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2290."},
  {"name": "صناعة الورق", "logo": "/logos/tadawul/2300.png", "url": "https://www.google.com/finance/quote/2300:TADAWUL", "brief": "صناعة الورق — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2300."},
  {"name": "سبكيم العالمية", "logo": "/logos/tadawul/2310.png", "url": "https://www.google.com/finance/quote/2310:TADAWUL", "brief": "سبكيم العالمية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2310."},
  {"name": "المتقدمة", "logo": "/logos/tadawul/2330.png", "url": "https://www.google.com/finance/quote/2330:TADAWUL", "brief": "المتقدمة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2330."},
  {"name": "كيان السعودية", "logo": "/logos/tadawul/2350.png", "url": "https://www.google.com/finance/quote/2350:TADAWUL", "brief": "كيان السعودية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2350."},
  {"name": "الفخارية", "logo": "/logos/tadawul/2360.png", "url": "https://www.google.com/finance/quote/2360:TADAWUL", "brief": "الفخارية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2360."},
  {"name": "أسمنت نجران", "logo": "/logos/tadawul/3002.png", "url": "https://www.google.com/finance/quote/3002:TADAWUL", "brief": "أسمنت نجران — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3002."},
  {"name": "أسمنت المدينة", "logo": "/logos/tadawul/3003.png", "url": "https://www.google.com/finance/quote/3003:TADAWUL", "brief": "أسمنت المدينة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3003."},
  {"name": "أسمنت الشمالية", "logo": "/logos/tadawul/3004.png", "url": "https://www.google.com/finance/quote/3004:TADAWUL", "brief": "أسمنت الشمالية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3004."},
  {"name": "أسمنت ام القرى", "logo": "/logos/tadawul/3005.png", "url": "https://www.google.com/finance/quote/3005:TADAWUL", "brief": "أسمنت ام القرى — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3005."},
  {"name": "الواحة", "logo": "/logos/tadawul/3007.png", "url": "https://www.google.com/finance/quote/3007:TADAWUL", "brief": "الواحة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3007."},
  {"name": "الكثيري", "logo": "/logos/tadawul/3008.png", "url": "https://www.google.com/finance/quote/3008:TADAWUL", "brief": "الكثيري — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3008."},
  {"name": "أسمنت العربية", "logo": "/logos/tadawul/3010.png", "url": "https://www.google.com/finance/quote/3010:TADAWUL", "brief": "أسمنت العربية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3010."},
  {"name": "أسمنت اليمامة", "logo": "/logos/tadawul/3020.png", "url": "https://www.google.com/finance/quote/3020:TADAWUL", "brief": "أسمنت اليمامة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3020."},
  {"name": "أسمنت السعودية", "logo": "/logos/tadawul/3030.png", "url": "https://www.google.com/finance/quote/3030:TADAWUL", "brief": "أسمنت السعودية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3030."},
  {"name": "أسمنت القصيم", "logo": "/logos/tadawul/3040.png", "url": "https://www.google.com/finance/quote/3040:TADAWUL", "brief": "أسمنت القصيم — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3040."},
  {"name": "أسمنت الجنوب", "logo": "/logos/tadawul/3050.png", "url": "https://www.google.com/finance/quote/3050:TADAWUL", "brief": "أسمنت الجنوب — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3050."},
  {"name": "أسمنت ينبع", "logo": "/logos/tadawul/3060.png", "url": "https://www.google.com/finance/quote/3060:TADAWUL", "brief": "أسمنت ينبع — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3060."},
  {"name": "أسمنت الشرقية", "logo": "/logos/tadawul/3080.png", "url": "https://www.google.com/finance/quote/3080:TADAWUL", "brief": "أسمنت الشرقية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3080."},
  {"name": "أسمنت تبوك", "logo": "/logos/tadawul/3090.png", "url": "https://www.google.com/finance/quote/3090:TADAWUL", "brief": "أسمنت تبوك — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3090."},
  {"name": "أسمنت الجوف", "logo": "/logos/tadawul/3091.png", "url": "https://www.google.com/finance/quote/3091:TADAWUL", "brief": "أسمنت الجوف — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3091."},
  {"name": "أسمنت الرياض", "logo": "/logos/tadawul/3092.png", "url": "https://www.google.com/finance/quote/3092:TADAWUL", "brief": "أسمنت الرياض — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 3092."},
  {"name": "تالكو", "logo": "/logos/tadawul/4143.png", "url": "https://www.google.com/finance/quote/4143:TADAWUL", "brief": "تالكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4143."},
  {"name": "أسترا الصناعية", "logo": "/logos/tadawul/1212.png", "url": "https://www.google.com/finance/quote/1212:TADAWUL", "brief": "أسترا الصناعية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1212."},
  {"name": "شاكر", "logo": "/logos/tadawul/1214.png", "url": "https://www.google.com/finance/quote/1214:TADAWUL", "brief": "شاكر — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1214."},
  {"name": "بوان", "logo": "/logos/tadawul/1302.png", "url": "https://www.google.com/finance/quote/1302:TADAWUL", "brief": "بوان — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1302."},
  {"name": "الصناعات الكهربائية", "logo": "/logos/tadawul/1303.png", "url": "https://www.google.com/finance/quote/1303:TADAWUL", "brief": "الصناعات الكهربائية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1303."},
  {"name": "الخزف السعودي", "logo": "/logos/tadawul/2040.png", "url": "https://www.google.com/finance/quote/2040:TADAWUL", "brief": "الخزف السعودي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2040."},
  {"name": "الكابلات السعودية", "logo": "/logos/tadawul/2110.png", "url": "https://www.google.com/finance/quote/2110:TADAWUL", "brief": "الكابلات السعودية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2110."},
  {"name": "أميانتيت", "logo": "/logos/tadawul/2160.png", "url": "https://www.google.com/finance/quote/2160:TADAWUL", "brief": "أميانتيت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2160."},
  {"name": "البابطين", "logo": "/logos/tadawul/2320.png", "url": "https://www.google.com/finance/quote/2320:TADAWUL", "brief": "البابطين — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2320."},
  {"name": "مسك", "logo": "/logos/tadawul/2370.png", "url": "https://www.google.com/finance/quote/2370:TADAWUL", "brief": "مسك — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2370."},
  {"name": "باتك", "logo": "/logos/tadawul/4110.png", "url": "https://www.google.com/finance/quote/4110:TADAWUL", "brief": "باتك — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4110."},
  {"name": "صادرات", "logo": "/logos/tadawul/4140.png", "url": "https://www.google.com/finance/quote/4140:TADAWUL", "brief": "صادرات — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4140."},
  {"name": "العمران", "logo": "/logos/tadawul/4141.png", "url": "https://www.google.com/finance/quote/4141:TADAWUL", "brief": "العمران — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4141."},
  {"name": "كابلات الرياض", "logo": "/logos/tadawul/4142.png", "url": "https://www.google.com/finance/quote/4142:TADAWUL", "brief": "كابلات الرياض — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4142."},
  {"name": "رؤوم", "logo": "/logos/tadawul/4144.png", "url": "https://www.google.com/finance/quote/4144:TADAWUL", "brief": "رؤوم — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4144."},
  {"name": "أو جي سي", "logo": "/logos/tadawul/4145.png", "url": "https://www.google.com/finance/quote/4145:TADAWUL", "brief": "أو جي سي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4145."},
  {"name": "جاز", "logo": "/logos/tadawul/4146.png", "url": "https://www.google.com/finance/quote/4146:TADAWUL", "brief": "جاز — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4146."},
  {"name": "سي جي إس", "logo": "/logos/tadawul/4147.png", "url": "https://www.google.com/finance/quote/4147:TADAWUL", "brief": "سي جي إس — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4147."},
  {"name": "الوسائل الصناعية", "logo": "/logos/tadawul/4148.png", "url": "https://www.google.com/finance/quote/4148:TADAWUL", "brief": "الوسائل الصناعية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4148."},
  {"name": "مهارة", "logo": "/logos/tadawul/1831.png", "url": "https://www.google.com/finance/quote/1831:TADAWUL", "brief": "مهارة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1831."},
  {"name": "صدر", "logo": "/logos/tadawul/1832.png", "url": "https://www.google.com/finance/quote/1832:TADAWUL", "brief": "صدر — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1832."},
  {"name": "الموارد", "logo": "/logos/tadawul/1833.png", "url": "https://www.google.com/finance/quote/1833:TADAWUL", "brief": "الموارد — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1833."},
  {"name": "سماسكو", "logo": "/logos/tadawul/1834.png", "url": "https://www.google.com/finance/quote/1834:TADAWUL", "brief": "سماسكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1834."},
  {"name": "تمكين", "logo": "/logos/tadawul/1835.png", "url": "https://www.google.com/finance/quote/1835:TADAWUL", "brief": "تمكين — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1835."},
  {"name": "طباعة وتغليف", "logo": "/logos/tadawul/4270.png", "url": "https://www.google.com/finance/quote/4270:TADAWUL", "brief": "طباعة وتغليف — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4270."},
  {"name": "كاتريون", "logo": "/logos/tadawul/6004.png", "url": "https://www.google.com/finance/quote/6004:TADAWUL", "brief": "كاتريون — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6004."},
  {"name": "سيسكو القابضة", "logo": "/logos/tadawul/2190.png", "url": "https://www.google.com/finance/quote/2190:TADAWUL", "brief": "سيسكو القابضة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2190."},
  {"name": "الخدمات الأرضية", "logo": "/logos/tadawul/4031.png", "url": "https://www.google.com/finance/quote/4031:TADAWUL", "brief": "الخدمات الأرضية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4031."},
  {"name": "سابتكو", "logo": "/logos/tadawul/4040.png", "url": "https://www.google.com/finance/quote/4040:TADAWUL", "brief": "سابتكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4040."},
  {"name": "بدجت السعودية", "logo": "/logos/tadawul/4260.png", "url": "https://www.google.com/finance/quote/4260:TADAWUL", "brief": "بدجت السعودية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4260."},
  {"name": "ذيب", "logo": "/logos/tadawul/4261.png", "url": "https://www.google.com/finance/quote/4261:TADAWUL", "brief": "ذيب — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4261."},
  {"name": "لومي", "logo": "/logos/tadawul/4262.png", "url": "https://www.google.com/finance/quote/4262:TADAWUL", "brief": "لومي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4262."},
  {"name": "سال", "logo": "/logos/tadawul/4263.png", "url": "https://www.google.com/finance/quote/4263:TADAWUL", "brief": "سال — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4263."},
  {"name": "طيران ناس", "logo": "/logos/tadawul/4264.png", "url": "https://www.google.com/finance/quote/4264:TADAWUL", "brief": "طيران ناس — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4264."},
  {"name": "شري", "logo": "/logos/tadawul/4265.png", "url": "https://www.google.com/finance/quote/4265:TADAWUL", "brief": "شري — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4265."},
  {"name": "نسيج", "logo": "/logos/tadawul/1213.png", "url": "https://www.google.com/finance/quote/1213:TADAWUL", "brief": "نسيج — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1213."},
  {"name": "صدق", "logo": "/logos/tadawul/2130.png", "url": "https://www.google.com/finance/quote/2130:TADAWUL", "brief": "صدق — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2130."},
  {"name": "ارتيكس", "logo": "/logos/tadawul/2340.png", "url": "https://www.google.com/finance/quote/2340:TADAWUL", "brief": "ارتيكس — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2340."},
  {"name": "لازوردي", "logo": "/logos/tadawul/4011.png", "url": "https://www.google.com/finance/quote/4011:TADAWUL", "brief": "لازوردي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4011."},
  {"name": "الأصيل", "logo": "/logos/tadawul/4012.png", "url": "https://www.google.com/finance/quote/4012:TADAWUL", "brief": "الأصيل — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4012."},
  {"name": "مجموعة فتيحي", "logo": "/logos/tadawul/4180.png", "url": "https://www.google.com/finance/quote/4180:TADAWUL", "brief": "مجموعة فتيحي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4180."},
  {"name": "سيرا", "logo": "/logos/tadawul/1810.png", "url": "https://www.google.com/finance/quote/1810:TADAWUL", "brief": "سيرا — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1810."},
  {"name": "بان", "logo": "/logos/tadawul/1820.png", "url": "https://www.google.com/finance/quote/1820:TADAWUL", "brief": "بان — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1820."},
  {"name": "لجام للرياضة", "logo": "/logos/tadawul/1830.png", "url": "https://www.google.com/finance/quote/1830:TADAWUL", "brief": "لجام للرياضة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1830."},
  {"name": "شمس", "logo": "/logos/tadawul/4170.png", "url": "https://www.google.com/finance/quote/4170:TADAWUL", "brief": "شمس — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4170."},
  {"name": "الخليج للتدريب", "logo": "/logos/tadawul/4290.png", "url": "https://www.google.com/finance/quote/4290:TADAWUL", "brief": "الخليج للتدريب — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4290."},
  {"name": "الوطنية للتعليم", "logo": "/logos/tadawul/4291.png", "url": "https://www.google.com/finance/quote/4291:TADAWUL", "brief": "الوطنية للتعليم — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4291."},
  {"name": "عطاء", "logo": "/logos/tadawul/4292.png", "url": "https://www.google.com/finance/quote/4292:TADAWUL", "brief": "عطاء — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4292."},
  {"name": "هرفي للأغذية", "logo": "/logos/tadawul/6002.png", "url": "https://www.google.com/finance/quote/6002:TADAWUL", "brief": "هرفي للأغذية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6002."},
  {"name": "ريدان", "logo": "/logos/tadawul/6012.png", "url": "https://www.google.com/finance/quote/6012:TADAWUL", "brief": "ريدان — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6012."},
  {"name": "التطويرية الغذائية", "logo": "/logos/tadawul/6013.png", "url": "https://www.google.com/finance/quote/6013:TADAWUL", "brief": "التطويرية الغذائية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6013."},
  {"name": "الآمار", "logo": "/logos/tadawul/6014.png", "url": "https://www.google.com/finance/quote/6014:TADAWUL", "brief": "الآمار — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6014."},
  {"name": "أمريكانا", "logo": "/logos/tadawul/6015.png", "url": "https://www.google.com/finance/quote/6015:TADAWUL", "brief": "أمريكانا — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6015."},
  {"name": "برغرايززر", "logo": "/logos/tadawul/6016.png", "url": "https://www.google.com/finance/quote/6016:TADAWUL", "brief": "برغرايززر — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6016."},
  {"name": "جاهز", "logo": "/logos/tadawul/6017.png", "url": "https://www.google.com/finance/quote/6017:TADAWUL", "brief": "جاهز — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6017."},
  {"name": "الأندية للرياضة", "logo": "/logos/tadawul/6018.png", "url": "https://www.google.com/finance/quote/6018:TADAWUL", "brief": "الأندية للرياضة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6018."},
  {"name": "المسار الشامل", "logo": "/logos/tadawul/6019.png", "url": "https://www.google.com/finance/quote/6019:TADAWUL", "brief": "المسار الشامل — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6019."},
  {"name": "تهامة", "logo": "/logos/tadawul/4070.png", "url": "https://www.google.com/finance/quote/4070:TADAWUL", "brief": "تهامة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4070."},
  {"name": "العربية", "logo": "/logos/tadawul/4071.png", "url": "https://www.google.com/finance/quote/4071:TADAWUL", "brief": "العربية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4071."},
  {"name": "مجموعة إم بي سي", "logo": "/logos/tadawul/4072.png", "url": "https://www.google.com/finance/quote/4072:TADAWUL", "brief": "مجموعة إم بي سي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4072."},
  {"name": "الأبحاث والإعلام", "logo": "/logos/tadawul/4210.png", "url": "https://www.google.com/finance/quote/4210:TADAWUL", "brief": "الأبحاث والإعلام — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4210."},
  {"name": "إكسترا", "logo": "/logos/tadawul/4003.png", "url": "https://www.google.com/finance/quote/4003:TADAWUL", "brief": "إكسترا — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4003."},
  {"name": "ساكو", "logo": "/logos/tadawul/4008.png", "url": "https://www.google.com/finance/quote/4008:TADAWUL", "brief": "ساكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4008."},
  {"name": "ساسكو", "logo": "/logos/tadawul/4050.png", "url": "https://www.google.com/finance/quote/4050:TADAWUL", "brief": "ساسكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4050."},
  {"name": "باعظيم", "logo": "/logos/tadawul/4051.png", "url": "https://www.google.com/finance/quote/4051:TADAWUL", "brief": "باعظيم — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4051."},
  {"name": "جرير", "logo": "/logos/tadawul/4190.png", "url": "https://www.google.com/finance/quote/4190:TADAWUL", "brief": "جرير — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4190."},
  {"name": "أبو معطي", "logo": "/logos/tadawul/4191.png", "url": "https://www.google.com/finance/quote/4191:TADAWUL", "brief": "أبو معطي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4191."},
  {"name": "السيف غاليري", "logo": "/logos/tadawul/4192.png", "url": "https://www.google.com/finance/quote/4192:TADAWUL", "brief": "السيف غاليري — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4192."},
  {"name": "نايس ون", "logo": "/logos/tadawul/4193.png", "url": "https://www.google.com/finance/quote/4193:TADAWUL", "brief": "نايس ون — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4193."},
  {"name": "محطة البناء", "logo": "/logos/tadawul/4194.png", "url": "https://www.google.com/finance/quote/4194:TADAWUL", "brief": "محطة البناء — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4194."},
  {"name": "الدريس", "logo": "/logos/tadawul/4200.png", "url": "https://www.google.com/finance/quote/4200:TADAWUL", "brief": "الدريس — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4200."},
  {"name": "سينومي ريتيل", "logo": "/logos/tadawul/4240.png", "url": "https://www.google.com/finance/quote/4240:TADAWUL", "brief": "سينومي ريتيل — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4240."},
  {"name": "أسواق ع العثيم", "logo": "/logos/tadawul/4001.png", "url": "https://www.google.com/finance/quote/4001:TADAWUL", "brief": "أسواق ع العثيم — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4001."},
  {"name": "أسواق المزرعة", "logo": "/logos/tadawul/4006.png", "url": "https://www.google.com/finance/quote/4006:TADAWUL", "brief": "أسواق المزرعة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4006."},
  {"name": "أنعام القابضة", "logo": "/logos/tadawul/4061.png", "url": "https://www.google.com/finance/quote/4061:TADAWUL", "brief": "أنعام القابضة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4061."},
  {"name": "ثمار", "logo": "/logos/tadawul/4160.png", "url": "https://www.google.com/finance/quote/4160:TADAWUL", "brief": "ثمار — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4160."},
  {"name": "بن داود", "logo": "/logos/tadawul/4161.png", "url": "https://www.google.com/finance/quote/4161:TADAWUL", "brief": "بن داود — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4161."},
  {"name": "المنجم", "logo": "/logos/tadawul/4162.png", "url": "https://www.google.com/finance/quote/4162:TADAWUL", "brief": "المنجم — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4162."},
  {"name": "الدواء", "logo": "/logos/tadawul/4163.png", "url": "https://www.google.com/finance/quote/4163:TADAWUL", "brief": "الدواء — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4163."},
  {"name": "النهدي", "logo": "/logos/tadawul/4164.png", "url": "https://www.google.com/finance/quote/4164:TADAWUL", "brief": "النهدي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4164."},
  {"name": "مجموعة صافولا", "logo": "/logos/tadawul/2050.png", "url": "https://www.google.com/finance/quote/2050:TADAWUL", "brief": "مجموعة صافولا — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2050."},
  {"name": "وفرة", "logo": "/logos/tadawul/2100.png", "url": "https://www.google.com/finance/quote/2100:TADAWUL", "brief": "وفرة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2100."},
  {"name": "سدافكو", "logo": "/logos/tadawul/2270.png", "url": "https://www.google.com/finance/quote/2270:TADAWUL", "brief": "سدافكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2270."},
  {"name": "المراعي", "logo": "/logos/tadawul/2280.png", "url": "https://www.google.com/finance/quote/2280:TADAWUL", "brief": "المراعي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2280."},
  {"name": "تنمية", "logo": "/logos/tadawul/2281.png", "url": "https://www.google.com/finance/quote/2281:TADAWUL", "brief": "تنمية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2281."},
  {"name": "نقي", "logo": "/logos/tadawul/2282.png", "url": "https://www.google.com/finance/quote/2282:TADAWUL", "brief": "نقي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2282."},
  {"name": "المطاحن الأولى", "logo": "/logos/tadawul/2283.png", "url": "https://www.google.com/finance/quote/2283:TADAWUL", "brief": "المطاحن الأولى — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2283."},
  {"name": "المطاحن الحديثة", "logo": "/logos/tadawul/2284.png", "url": "https://www.google.com/finance/quote/2284:TADAWUL", "brief": "المطاحن الحديثة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2284."},
  {"name": "المطاحن العربية", "logo": "/logos/tadawul/2285.png", "url": "https://www.google.com/finance/quote/2285:TADAWUL", "brief": "المطاحن العربية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2285."},
  {"name": "المطاحن الرابعة", "logo": "/logos/tadawul/2286.png", "url": "https://www.google.com/finance/quote/2286:TADAWUL", "brief": "المطاحن الرابعة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2286."},
  {"name": "إنتاج", "logo": "/logos/tadawul/2287.png", "url": "https://www.google.com/finance/quote/2287:TADAWUL", "brief": "إنتاج — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2287."},
  {"name": "نفوذ", "logo": "/logos/tadawul/2288.png", "url": "https://www.google.com/finance/quote/2288:TADAWUL", "brief": "نفوذ — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2288."},
  {"name": "سناد القابضة", "logo": "/logos/tadawul/4080.png", "url": "https://www.google.com/finance/quote/4080:TADAWUL", "brief": "سناد القابضة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4080."},
  {"name": "حلواني إخوان", "logo": "/logos/tadawul/6001.png", "url": "https://www.google.com/finance/quote/6001:TADAWUL", "brief": "حلواني إخوان — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6001."},
  {"name": "نادك", "logo": "/logos/tadawul/6010.png", "url": "https://www.google.com/finance/quote/6010:TADAWUL", "brief": "نادك — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6010."},
  {"name": "جاكو", "logo": "/logos/tadawul/6020.png", "url": "https://www.google.com/finance/quote/6020:TADAWUL", "brief": "جاكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6020."},
  {"name": "تبوك الزراعية", "logo": "/logos/tadawul/6040.png", "url": "https://www.google.com/finance/quote/6040:TADAWUL", "brief": "تبوك الزراعية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6040."},
  {"name": "الأسماك", "logo": "/logos/tadawul/6050.png", "url": "https://www.google.com/finance/quote/6050:TADAWUL", "brief": "الأسماك — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6050."},
  {"name": "الشرقية للتنمية", "logo": "/logos/tadawul/6060.png", "url": "https://www.google.com/finance/quote/6060:TADAWUL", "brief": "الشرقية للتنمية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6060."},
  {"name": "الجوف", "logo": "/logos/tadawul/6070.png", "url": "https://www.google.com/finance/quote/6070:TADAWUL", "brief": "الجوف — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6070."},
  {"name": "جازادكو", "logo": "/logos/tadawul/6090.png", "url": "https://www.google.com/finance/quote/6090:TADAWUL", "brief": "جازادكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 6090."},
  {"name": "الماجد للعود", "logo": "/logos/tadawul/4165.png", "url": "https://www.google.com/finance/quote/4165:TADAWUL", "brief": "الماجد للعود — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4165."},
  {"name": "أيان", "logo": "/logos/tadawul/2140.png", "url": "https://www.google.com/finance/quote/2140:TADAWUL", "brief": "أيان — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2140."},
  {"name": "الكيميائية", "logo": "/logos/tadawul/2230.png", "url": "https://www.google.com/finance/quote/2230:TADAWUL", "brief": "الكيميائية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2230."},
  {"name": "المواساة", "logo": "/logos/tadawul/4002.png", "url": "https://www.google.com/finance/quote/4002:TADAWUL", "brief": "المواساة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4002."},
  {"name": "دله الصحية", "logo": "/logos/tadawul/4004.png", "url": "https://www.google.com/finance/quote/4004:TADAWUL", "brief": "دله الصحية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4004."},
  {"name": "رعاية", "logo": "/logos/tadawul/4005.png", "url": "https://www.google.com/finance/quote/4005:TADAWUL", "brief": "رعاية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4005."},
  {"name": "الحمادي", "logo": "/logos/tadawul/4007.png", "url": "https://www.google.com/finance/quote/4007:TADAWUL", "brief": "الحمادي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4007."},
  {"name": "السعودي الألماني الصحية", "logo": "/logos/tadawul/4009.png", "url": "https://www.google.com/finance/quote/4009:TADAWUL", "brief": "السعودي الألماني الصحية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4009."},
  {"name": "سليمان الحبيب", "logo": "/logos/tadawul/4013.png", "url": "https://www.google.com/finance/quote/4013:TADAWUL", "brief": "سليمان الحبيب — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4013."},
  {"name": "دار المعدات", "logo": "/logos/tadawul/4014.png", "url": "https://www.google.com/finance/quote/4014:TADAWUL", "brief": "دار المعدات — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4014."},
  {"name": "فقيه الطبية", "logo": "/logos/tadawul/4017.png", "url": "https://www.google.com/finance/quote/4017:TADAWUL", "brief": "فقيه الطبية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4017."},
  {"name": "الموسى", "logo": "/logos/tadawul/4018.png", "url": "https://www.google.com/finance/quote/4018:TADAWUL", "brief": "الموسى — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4018."},
  {"name": "اس ام سي للرعاية الصحية", "logo": "/logos/tadawul/4019.png", "url": "https://www.google.com/finance/quote/4019:TADAWUL", "brief": "اس ام سي للرعاية الصحية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4019."},
  {"name": "المركز الكندي الطبي", "logo": "/logos/tadawul/4021.png", "url": "https://www.google.com/finance/quote/4021:TADAWUL", "brief": "المركز الكندي الطبي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4021."},
  {"name": "الدوائية", "logo": "/logos/tadawul/2070.png", "url": "https://www.google.com/finance/quote/2070:TADAWUL", "brief": "الدوائية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2070."},
  {"name": "جمجوم فارما", "logo": "/logos/tadawul/4015.png", "url": "https://www.google.com/finance/quote/4015:TADAWUL", "brief": "جمجوم فارما — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4015."},
  {"name": "أفالون فارما", "logo": "/logos/tadawul/4016.png", "url": "https://www.google.com/finance/quote/4016:TADAWUL", "brief": "أفالون فارما — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4016."},
  {"name": "الرياض", "logo": "/logos/tadawul/1010.png", "url": "https://www.google.com/finance/quote/1010:TADAWUL", "brief": "الرياض — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1010."},
  {"name": "الجزيرة", "logo": "/logos/tadawul/1020.png", "url": "https://www.google.com/finance/quote/1020:TADAWUL", "brief": "الجزيرة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1020."},
  {"name": "الإستثمار", "logo": "/logos/tadawul/1030.png", "url": "https://www.google.com/finance/quote/1030:TADAWUL", "brief": "الإستثمار — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1030."},
  {"name": "بي اس اف", "logo": "/logos/tadawul/1050.png", "url": "https://www.google.com/finance/quote/1050:TADAWUL", "brief": "بي اس اف — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1050."},
  {"name": "الأول", "logo": "/logos/tadawul/1060.png", "url": "https://www.google.com/finance/quote/1060:TADAWUL", "brief": "الأول — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1060."},
  {"name": "العربي", "logo": "/logos/tadawul/1080.png", "url": "https://www.google.com/finance/quote/1080:TADAWUL", "brief": "العربي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1080."},
  {"name": "الراجحي", "logo": "/logos/tadawul/1120.png", "url": "https://www.google.com/finance/quote/1120:TADAWUL", "brief": "الراجحي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1120."},
  {"name": "البلاد", "logo": "/logos/tadawul/1140.png", "url": "https://www.google.com/finance/quote/1140:TADAWUL", "brief": "البلاد — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1140."},
  {"name": "الإنماء", "logo": "/logos/tadawul/1150.png", "url": "https://www.google.com/finance/quote/1150:TADAWUL", "brief": "الإنماء — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1150."},
  {"name": "الأهلي", "logo": "/logos/tadawul/1180.png", "url": "https://www.google.com/finance/quote/1180:TADAWUL", "brief": "الأهلي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1180."},
  {"name": "مجموعة تداول", "logo": "/logos/tadawul/1111.png", "url": "https://www.google.com/finance/quote/1111:TADAWUL", "brief": "مجموعة تداول — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1111."},
  {"name": "أملاك", "logo": "/logos/tadawul/1182.png", "url": "https://www.google.com/finance/quote/1182:TADAWUL", "brief": "أملاك — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1182."},
  {"name": "سهل", "logo": "/logos/tadawul/1183.png", "url": "https://www.google.com/finance/quote/1183:TADAWUL", "brief": "سهل — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 1183."},
  {"name": "متطورة", "logo": "/logos/tadawul/2120.png", "url": "https://www.google.com/finance/quote/2120:TADAWUL", "brief": "متطورة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2120."},
  {"name": "النايفات", "logo": "/logos/tadawul/4081.png", "url": "https://www.google.com/finance/quote/4081:TADAWUL", "brief": "النايفات — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4081."},
  {"name": "مرنة", "logo": "/logos/tadawul/4082.png", "url": "https://www.google.com/finance/quote/4082:TADAWUL", "brief": "مرنة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4082."},
  {"name": "تسهيل", "logo": "/logos/tadawul/4083.png", "url": "https://www.google.com/finance/quote/4083:TADAWUL", "brief": "تسهيل — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4083."},
  {"name": "دراية", "logo": "/logos/tadawul/4084.png", "url": "https://www.google.com/finance/quote/4084:TADAWUL", "brief": "دراية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4084."},
  {"name": "درب السعودية", "logo": "/logos/tadawul/4130.png", "url": "https://www.google.com/finance/quote/4130:TADAWUL", "brief": "درب السعودية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4130."},
  {"name": "المملكة", "logo": "/logos/tadawul/4280.png", "url": "https://www.google.com/finance/quote/4280:TADAWUL", "brief": "المملكة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4280."},
  {"name": "التعاونية", "logo": "/logos/tadawul/8010.png", "url": "https://www.google.com/finance/quote/8010:TADAWUL", "brief": "التعاونية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8010."},
  {"name": "جزيرة تكافل", "logo": "/logos/tadawul/8012.png", "url": "https://www.google.com/finance/quote/8012:TADAWUL", "brief": "جزيرة تكافل — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8012."},
  {"name": "ملاذ للتأمين", "logo": "/logos/tadawul/8020.png", "url": "https://www.google.com/finance/quote/8020:TADAWUL", "brief": "ملاذ للتأمين — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8020."},
  {"name": "ميدغلف للتأمين", "logo": "/logos/tadawul/8030.png", "url": "https://www.google.com/finance/quote/8030:TADAWUL", "brief": "ميدغلف للتأمين — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8030."},
  {"name": "متكاملة", "logo": "/logos/tadawul/8040.png", "url": "https://www.google.com/finance/quote/8040:TADAWUL", "brief": "متكاملة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8040."},
  {"name": "سلامة", "logo": "/logos/tadawul/8050.png", "url": "https://www.google.com/finance/quote/8050:TADAWUL", "brief": "سلامة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8050."},
  {"name": "ولاء", "logo": "/logos/tadawul/8060.png", "url": "https://www.google.com/finance/quote/8060:TADAWUL", "brief": "ولاء — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8060."},
  {"name": "الدرع العربي", "logo": "/logos/tadawul/8070.png", "url": "https://www.google.com/finance/quote/8070:TADAWUL", "brief": "الدرع العربي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8070."},
  {"name": "سايكو", "logo": "/logos/tadawul/8100.png", "url": "https://www.google.com/finance/quote/8100:TADAWUL", "brief": "سايكو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8100."},
  {"name": "إتحاد الخليج الأهلية", "logo": "/logos/tadawul/8120.png", "url": "https://www.google.com/finance/quote/8120:TADAWUL", "brief": "إتحاد الخليج الأهلية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8120."},
  {"name": "أسيج", "logo": "/logos/tadawul/8150.png", "url": "https://www.google.com/finance/quote/8150:TADAWUL", "brief": "أسيج — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8150."},
  {"name": "التأمين العربية", "logo": "/logos/tadawul/8160.png", "url": "https://www.google.com/finance/quote/8160:TADAWUL", "brief": "التأمين العربية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8160."},
  {"name": "الاتحاد", "logo": "/logos/tadawul/8170.png", "url": "https://www.google.com/finance/quote/8170:TADAWUL", "brief": "الاتحاد — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8170."},
  {"name": "الصقر للتأمين", "logo": "/logos/tadawul/8180.png", "url": "https://www.google.com/finance/quote/8180:TADAWUL", "brief": "الصقر للتأمين — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8180."},
  {"name": "المتحدة للتأمين", "logo": "/logos/tadawul/8190.png", "url": "https://www.google.com/finance/quote/8190:TADAWUL", "brief": "المتحدة للتأمين — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8190."},
  {"name": "الإعادة السعودية", "logo": "/logos/tadawul/8200.png", "url": "https://www.google.com/finance/quote/8200:TADAWUL", "brief": "الإعادة السعودية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8200."},
  {"name": "بوبا العربية", "logo": "/logos/tadawul/8210.png", "url": "https://www.google.com/finance/quote/8210:TADAWUL", "brief": "بوبا العربية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8210."},
  {"name": "تكافل الراجحي", "logo": "/logos/tadawul/8230.png", "url": "https://www.google.com/finance/quote/8230:TADAWUL", "brief": "تكافل الراجحي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8230."},
  {"name": "تْشب", "logo": "/logos/tadawul/8240.png", "url": "https://www.google.com/finance/quote/8240:TADAWUL", "brief": "تْشب — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8240."},
  {"name": "جي آي جي", "logo": "/logos/tadawul/8250.png", "url": "https://www.google.com/finance/quote/8250:TADAWUL", "brief": "جي آي جي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8250."},
  {"name": "الخليجية العامة", "logo": "/logos/tadawul/8260.png", "url": "https://www.google.com/finance/quote/8260:TADAWUL", "brief": "الخليجية العامة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8260."},
  {"name": "ليفا", "logo": "/logos/tadawul/8280.png", "url": "https://www.google.com/finance/quote/8280:TADAWUL", "brief": "ليفا — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8280."},
  {"name": "الوطنية", "logo": "/logos/tadawul/8300.png", "url": "https://www.google.com/finance/quote/8300:TADAWUL", "brief": "الوطنية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8300."},
  {"name": "أمانة للتأمين", "logo": "/logos/tadawul/8310.png", "url": "https://www.google.com/finance/quote/8310:TADAWUL", "brief": "أمانة للتأمين — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8310."},
  {"name": "عناية", "logo": "/logos/tadawul/8311.png", "url": "https://www.google.com/finance/quote/8311:TADAWUL", "brief": "عناية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8311."},
  {"name": "رسن", "logo": "/logos/tadawul/8313.png", "url": "https://www.google.com/finance/quote/8313:TADAWUL", "brief": "رسن — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 8313."},
  {"name": "ام آي اس", "logo": "/logos/tadawul/7200.png", "url": "https://www.google.com/finance/quote/7200:TADAWUL", "brief": "ام آي اس — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 7200."},
  {"name": "بحر العرب", "logo": "/logos/tadawul/7201.png", "url": "https://www.google.com/finance/quote/7201:TADAWUL", "brief": "بحر العرب — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 7201."},
  {"name": "سلوشنز", "logo": "/logos/tadawul/7202.png", "url": "https://www.google.com/finance/quote/7202:TADAWUL", "brief": "سلوشنز — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 7202."},
  {"name": "علم", "logo": "/logos/tadawul/7203.png", "url": "https://www.google.com/finance/quote/7203:TADAWUL", "brief": "علم — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 7203."},
  {"name": "توبي", "logo": "/logos/tadawul/7204.png", "url": "https://www.google.com/finance/quote/7204:TADAWUL", "brief": "توبي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 7204."},
  {"name": "دي بي اس", "logo": "/logos/tadawul/7205.png", "url": "https://www.google.com/finance/quote/7205:TADAWUL", "brief": "دي بي اس — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 7205."},
  {"name": "عزم", "logo": "/logos/tadawul/7211.png", "url": "https://www.google.com/finance/quote/7211:TADAWUL", "brief": "عزم — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 7211."},
  {"name": "اس تي سي", "logo": "/logos/tadawul/7010.png", "url": "https://www.google.com/finance/quote/7010:TADAWUL", "brief": "اس تي سي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 7010."},
  {"name": "إتحاد إتصالات", "logo": "/logos/tadawul/7020.png", "url": "https://www.google.com/finance/quote/7020:TADAWUL", "brief": "إتحاد إتصالات — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 7020."},
  {"name": "زين السعودية", "logo": "/logos/tadawul/7030.png", "url": "https://www.google.com/finance/quote/7030:TADAWUL", "brief": "زين السعودية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 7030."},
  {"name": "قو للإتصالات", "logo": "/logos/tadawul/7040.png", "url": "https://www.google.com/finance/quote/7040:TADAWUL", "brief": "قو للإتصالات — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 7040."},
  {"name": "الغاز", "logo": "/logos/tadawul/2080.png", "url": "https://www.google.com/finance/quote/2080:TADAWUL", "brief": "الغاز — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2080."},
  {"name": "الخريف", "logo": "/logos/tadawul/2081.png", "url": "https://www.google.com/finance/quote/2081:TADAWUL", "brief": "الخريف — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2081."},
  {"name": "أكوا", "logo": "/logos/tadawul/2082.png", "url": "https://www.google.com/finance/quote/2082:TADAWUL", "brief": "أكوا — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2082."},
  {"name": "مرافق", "logo": "/logos/tadawul/2083.png", "url": "https://www.google.com/finance/quote/2083:TADAWUL", "brief": "مرافق — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2083."},
  {"name": "مياهنا", "logo": "/logos/tadawul/2084.png", "url": "https://www.google.com/finance/quote/2084:TADAWUL", "brief": "مياهنا — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 2084."},
  {"name": "السعودية للطاقة", "logo": "/logos/tadawul/5110.png", "url": "https://www.google.com/finance/quote/5110:TADAWUL", "brief": "السعودية للطاقة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 5110."},
  {"name": "الرياض ريت", "logo": "/logos/tadawul/4330.png", "url": "https://www.google.com/finance/quote/4330:TADAWUL", "brief": "الرياض ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4330."},
  {"name": "الجزيرة ريت", "logo": "/logos/tadawul/4331.png", "url": "https://www.google.com/finance/quote/4331:TADAWUL", "brief": "الجزيرة ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4331."},
  {"name": "جدوى ريت الحرمين", "logo": "/logos/tadawul/4332.png", "url": "https://www.google.com/finance/quote/4332:TADAWUL", "brief": "جدوى ريت الحرمين — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4332."},
  {"name": "تعليم ريت", "logo": "/logos/tadawul/4333.png", "url": "https://www.google.com/finance/quote/4333:TADAWUL", "brief": "تعليم ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4333."},
  {"name": "المعذر ريت", "logo": "/logos/tadawul/4334.png", "url": "https://www.google.com/finance/quote/4334:TADAWUL", "brief": "المعذر ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4334."},
  {"name": "مشاركة ريت", "logo": "/logos/tadawul/4335.png", "url": "https://www.google.com/finance/quote/4335:TADAWUL", "brief": "مشاركة ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4335."},
  {"name": "ملكية ريت", "logo": "/logos/tadawul/4336.png", "url": "https://www.google.com/finance/quote/4336:TADAWUL", "brief": "ملكية ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4336."},
  {"name": "العزيزية ريت", "logo": "/logos/tadawul/4337.png", "url": "https://www.google.com/finance/quote/4337:TADAWUL", "brief": "العزيزية ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4337."},
  {"name": "الأهلي ريت 1", "logo": "/logos/tadawul/4338.png", "url": "https://www.google.com/finance/quote/4338:TADAWUL", "brief": "الأهلي ريت 1 — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4338."},
  {"name": "دراية ريت", "logo": "/logos/tadawul/4339.png", "url": "https://www.google.com/finance/quote/4339:TADAWUL", "brief": "دراية ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4339."},
  {"name": "الراجحي ريت", "logo": "/logos/tadawul/4340.png", "url": "https://www.google.com/finance/quote/4340:TADAWUL", "brief": "الراجحي ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4340."},
  {"name": "جدوى ريت السعودية", "logo": "/logos/tadawul/4342.png", "url": "https://www.google.com/finance/quote/4342:TADAWUL", "brief": "جدوى ريت السعودية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4342."},
  {"name": "سدكو كابيتال ريت", "logo": "/logos/tadawul/4344.png", "url": "https://www.google.com/finance/quote/4344:TADAWUL", "brief": "سدكو كابيتال ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4344."},
  {"name": "الإنماء ريت للتجزئة", "logo": "/logos/tadawul/4345.png", "url": "https://www.google.com/finance/quote/4345:TADAWUL", "brief": "الإنماء ريت للتجزئة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4345."},
  {"name": "ميفك ريت", "logo": "/logos/tadawul/4346.png", "url": "https://www.google.com/finance/quote/4346:TADAWUL", "brief": "ميفك ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4346."},
  {"name": "بنيان ريت", "logo": "/logos/tadawul/4347.png", "url": "https://www.google.com/finance/quote/4347:TADAWUL", "brief": "بنيان ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4347."},
  {"name": "الخبير ريت", "logo": "/logos/tadawul/4348.png", "url": "https://www.google.com/finance/quote/4348:TADAWUL", "brief": "الخبير ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4348."},
  {"name": "الإنماء ريت الفندقي", "logo": "/logos/tadawul/4349.png", "url": "https://www.google.com/finance/quote/4349:TADAWUL", "brief": "الإنماء ريت الفندقي — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4349."},
  {"name": "الإستثمار ريت", "logo": "/logos/tadawul/4350.png", "url": "https://www.google.com/finance/quote/4350:TADAWUL", "brief": "الإستثمار ريت — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4350."},
  {"name": "العقارية", "logo": "/logos/tadawul/4020.png", "url": "https://www.google.com/finance/quote/4020:TADAWUL", "brief": "العقارية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4020."},
  {"name": "طيبة", "logo": "/logos/tadawul/4090.png", "url": "https://www.google.com/finance/quote/4090:TADAWUL", "brief": "طيبة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4090."},
  {"name": "مكة", "logo": "/logos/tadawul/4100.png", "url": "https://www.google.com/finance/quote/4100:TADAWUL", "brief": "مكة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4100."},
  {"name": "التعمير", "logo": "/logos/tadawul/4150.png", "url": "https://www.google.com/finance/quote/4150:TADAWUL", "brief": "التعمير — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4150."},
  {"name": "إعمار", "logo": "/logos/tadawul/4220.png", "url": "https://www.google.com/finance/quote/4220:TADAWUL", "brief": "إعمار — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4220."},
  {"name": "البحر الأحمر", "logo": "/logos/tadawul/4230.png", "url": "https://www.google.com/finance/quote/4230:TADAWUL", "brief": "البحر الأحمر — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4230."},
  {"name": "جبل عمر", "logo": "/logos/tadawul/4250.png", "url": "https://www.google.com/finance/quote/4250:TADAWUL", "brief": "جبل عمر — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4250."},
  {"name": "دار الأركان", "logo": "/logos/tadawul/4300.png", "url": "https://www.google.com/finance/quote/4300:TADAWUL", "brief": "دار الأركان — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4300."},
  {"name": "مدينة المعرفة", "logo": "/logos/tadawul/4310.png", "url": "https://www.google.com/finance/quote/4310:TADAWUL", "brief": "مدينة المعرفة — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4310."},
  {"name": "الأندلس", "logo": "/logos/tadawul/4320.png", "url": "https://www.google.com/finance/quote/4320:TADAWUL", "brief": "الأندلس — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4320."},
  {"name": "سينومي سنترز", "logo": "/logos/tadawul/4321.png", "url": "https://www.google.com/finance/quote/4321:TADAWUL", "brief": "سينومي سنترز — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4321."},
  {"name": "رتال", "logo": "/logos/tadawul/4322.png", "url": "https://www.google.com/finance/quote/4322:TADAWUL", "brief": "رتال — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4322."},
  {"name": "سمو", "logo": "/logos/tadawul/4323.png", "url": "https://www.google.com/finance/quote/4323:TADAWUL", "brief": "سمو — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4323."},
  {"name": "بنان", "logo": "/logos/tadawul/4324.png", "url": "https://www.google.com/finance/quote/4324:TADAWUL", "brief": "بنان — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4324."},
  {"name": "مسار", "logo": "/logos/tadawul/4325.png", "url": "https://www.google.com/finance/quote/4325:TADAWUL", "brief": "مسار — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4325."},
  {"name": "الماجدية", "logo": "/logos/tadawul/4326.png", "url": "https://www.google.com/finance/quote/4326:TADAWUL", "brief": "الماجدية — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4326."},
  {"name": "الرمز", "logo": "/logos/tadawul/4327.png", "url": "https://www.google.com/finance/quote/4327:TADAWUL", "brief": "الرمز — شركة مدرجة في السوق المالية السعودية (تداول)، الرمز 4327."},
]
